{% set name = "bindensity" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bindensity-{{ version }}.tar.gz
  sha256: 3399767f60f90e9d48c922aef3f895a2732f4125985d1aa8486a15d8e46a9f77

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=61.0
    - wheel
    - numpy
    - pip
  run:
    - python

test:
  imports:
    - bindensity
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.unige.ch/delisle/bindensity
  summary: Suite of functions to manipulate bins densities and covariance matrices.
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbdelisle
